// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:b82d7869-6c7d-4b83-a624-310fb1241c66",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_W8p1gJhx8",
    "aws_user_pools_web_client_id": "373oci7c84kac6qecff9e9nsnh",
    "aws_appsync_graphqlEndpoint": "https://bx2lasf555fxnkkwstjbps5nga.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "octanappff038eb9b19242399ff639e90530442a",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
